# configuration for "Future" branch
-
  branches:
    only:
    - Future
  image: Visual Studio 2019
  configuration: Release
  build:
      parallel: true
      verbosity: quiet
  on_finish:
  - cmd: >-
       7z a DLL.zip %APPVEYOR_BUILD_FOLDER%\Release\D3DX9_42.dll

       appveyor PushArtifact DLL.zip
     
# configuration for "GUI" branch
-
  branches:
    only:
      - GUI
  image: Visual Studio 2019
  configuration: Release
  build:
    parallel: true
    verbosity: quiet
  on_finish:
  - cmd: >-
       7z a RSMods.zip %APPVEYOR_BUILD_FOLDER%\RSMods\bin\Release\*.* -r
     
       appveyor PushArtifact RSMods.zip
      
# configuration for "One-Click-Installer" branch      
-
  branches:
    only:
      - One-Click-Installer
  image: Visual Studio 2019
  configuration: Release
  skip_tags: true
  before_build:
    - cmd: >-
       del /S /q %APPVEYOR_BUILD_FOLDER%\Rocksmith2014-CDLC-Injector\Resources
       
       appveyor DownloadFile https://ci.appveyor.com/api/projects/Lovrom8/rscdlcenabler-2020edition/artifacts/RSMods.zip?branch=GUI
                
       appveyor DownloadFile https://ci.appveyor.com/api/projects/Lovrom8/rscdlcenabler-2020edition/artifacts/DLL.zip?branch=Future
            
       7z x RSMods.zip -o%APPVEYOR_BUILD_FOLDER%\Rocksmith2014-CDLC-Injector\Resources\RSModsGUI
                
       7z x DLL.zip -o%APPVEYOR_BUILD_FOLDER%\Rocksmith2014-CDLC-Injector\Resources\
  build:
    parallel: true
    verbosity: quiet
  artifacts:
  - path: '**\bin\Release\RS2014-Mod-Installer.exe'
    name: OneClick_Release
  deploy:
  - provider: GitHub
    tag: RSModsInstaller-v$(appveyor_build_version)
    release: RSModsInstaller-v$(appveyor_build_version)
    auth_token:
       secure: iGjQAEJQs6QvWb7qRiIvNPKshY1XviAbJcjt+QcIqGBQjcP/MzSejpINlgnm2ZzK
    artifact: OneClick_Release
    prerelease: true
      
