# configuration for "One-Click-Installer" branch      
-
  branches:
    only:
      - One-Click-Installer
  image: Visual Studio 2019
  configuration: Release
  skip_tags: true
  before_build:
    - ps: >-
        nuget restore

        $assemblyFile = "$env:APPVEYOR_BUILD_FOLDER\Rocksmith2014-Mod-Installer\Properties\AssemblyInfo.cs"

        $regex = new-object System.Text.RegularExpressions.Regex ('(AssemblyVersion(Attribute)?\s*\(\s*\")(.*)(\"\s*\))', [System.Text.RegularExpressions.RegexOptions]::MultiLine)

        $content = [IO.File]::ReadAllText($assemblyFile)

        $version = $null
        
        $match = $regex.Match($content)
        
        if($match.Success) {
            $version = $match.groups[3].value
        }
        
        $env:releaseVersion=$version
    - cmd: >-
       del /S /q %APPVEYOR_BUILD_FOLDER%\Rocksmith2014-Mod-Installer\Resources
       
       appveyor DownloadFile https://ci.appveyor.com/api/projects/Lovrom8/rscdlcenabler-2020edition/artifacts/RSMods.zip?branch=GUI
                
       appveyor DownloadFile https://ci.appveyor.com/api/projects/Lovrom8/rscdlcenabler-2020edition/artifacts/DLL.zip?branch=develop
            
       7z x RSMods.zip -o%APPVEYOR_BUILD_FOLDER%\Rocksmith2014-Mod-Installer\Resources\RSModsGUI
                
       7z x DLL.zip -o%APPVEYOR_BUILD_FOLDER%\Rocksmith2014-Mod-Installer\Resources\
  build:
    parallel: true
    verbosity: quiet
  artifacts:
  - path: '**\bin\Release\RS2014-Mod-Installer.exe'
    name: OneClick_Release
  deploy:
  - provider: GitHub
    tag: RSModsInstaller-v$(releaseVersion)
    release: RSModsInstaller-v$(releaseVersion)
    auth_token:
       secure: iGjQAEJQs6QvWb7qRiIvNPKshY1XviAbJcjt+QcIqGBQjcP/MzSejpINlgnm2ZzK
    artifact: OneClick_Release
    prerelease: true
      
