# configuration for "GUI" branch
-
  branches:
    only:
      - GUI
  image: Visual Studio 2019
  configuration: Release
  before_build:
  - ps: >-
        nuget restore
  build:
    parallel: true
    verbosity: quiet
  on_finish:
  - cmd: >-
       7z a RSMods.zip %APPVEYOR_BUILD_FOLDER%\RSMods\bin\x64\Release\*.* -r 
     
       appveyor PushArtifact RSMods.zip
